/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DemoObjectRouteImport } from './routes/demo/object'
import { Route as DemoChatRouteImport } from './routes/demo/chat'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardPortfolioRouteImport } from './routes/dashboard/portfolio'
import { Route as DashboardPlaygroundRouteImport } from './routes/dashboard/playground'
import { Route as DashboardOverviewRouteImport } from './routes/dashboard/overview'
import { Route as DashboardNetworkRouteImport } from './routes/dashboard/network'
import { Route as DashboardConnectorsRouteImport } from './routes/dashboard/connectors'
import { Route as ApiSeriesRouteImport } from './routes/api/series'
import { Route as ApiPortfolioGraphRouteImport } from './routes/api/portfolio-graph'
import { Route as ApiPerformanceRecipeRouteImport } from './routes/api/performance-recipe'
import { Route as ApiPerformanceFailureRouteImport } from './routes/api/performance-failure'
import { Route as ApiObjectRouteImport } from './routes/api/object'
import { Route as ApiMarketEventsRouteImport } from './routes/api/market-events'
import { Route as ApiGovImpactRouteImport } from './routes/api/gov-impact'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DemoObjectRoute = DemoObjectRouteImport.update({
  id: '/demo/object',
  path: '/demo/object',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoChatRoute = DemoChatRouteImport.update({
  id: '/demo/chat',
  path: '/demo/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPortfolioRoute = DashboardPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlaygroundRoute = DashboardPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNetworkRoute = DashboardNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConnectorsRoute = DashboardConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiSeriesRoute = ApiSeriesRouteImport.update({
  id: '/api/series',
  path: '/api/series',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortfolioGraphRoute = ApiPortfolioGraphRouteImport.update({
  id: '/api/portfolio-graph',
  path: '/api/portfolio-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPerformanceRecipeRoute = ApiPerformanceRecipeRouteImport.update({
  id: '/api/performance-recipe',
  path: '/api/performance-recipe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPerformanceFailureRoute = ApiPerformanceFailureRouteImport.update({
  id: '/api/performance-failure',
  path: '/api/performance-failure',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiObjectRoute = ApiObjectRouteImport.update({
  id: '/api/object',
  path: '/api/object',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketEventsRoute = ApiMarketEventsRouteImport.update({
  id: '/api/market-events',
  path: '/api/market-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGovImpactRoute = ApiGovImpactRouteImport.update({
  id: '/api/gov-impact',
  path: '/api/gov-impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/gov-impact': typeof ApiGovImpactRoute
  '/api/market-events': typeof ApiMarketEventsRoute
  '/api/object': typeof ApiObjectRoute
  '/api/performance-failure': typeof ApiPerformanceFailureRoute
  '/api/performance-recipe': typeof ApiPerformanceRecipeRoute
  '/api/portfolio-graph': typeof ApiPortfolioGraphRoute
  '/api/series': typeof ApiSeriesRoute
  '/dashboard/connectors': typeof DashboardConnectorsRoute
  '/dashboard/network': typeof DashboardNetworkRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/playground': typeof DashboardPlaygroundRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/demo/chat': typeof DemoChatRoute
  '/demo/object': typeof DemoObjectRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/gov-impact': typeof ApiGovImpactRoute
  '/api/market-events': typeof ApiMarketEventsRoute
  '/api/object': typeof ApiObjectRoute
  '/api/performance-failure': typeof ApiPerformanceFailureRoute
  '/api/performance-recipe': typeof ApiPerformanceRecipeRoute
  '/api/portfolio-graph': typeof ApiPortfolioGraphRoute
  '/api/series': typeof ApiSeriesRoute
  '/dashboard/connectors': typeof DashboardConnectorsRoute
  '/dashboard/network': typeof DashboardNetworkRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/playground': typeof DashboardPlaygroundRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/demo/chat': typeof DemoChatRoute
  '/demo/object': typeof DemoObjectRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/gov-impact': typeof ApiGovImpactRoute
  '/api/market-events': typeof ApiMarketEventsRoute
  '/api/object': typeof ApiObjectRoute
  '/api/performance-failure': typeof ApiPerformanceFailureRoute
  '/api/performance-recipe': typeof ApiPerformanceRecipeRoute
  '/api/portfolio-graph': typeof ApiPortfolioGraphRoute
  '/api/series': typeof ApiSeriesRoute
  '/dashboard/connectors': typeof DashboardConnectorsRoute
  '/dashboard/network': typeof DashboardNetworkRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/playground': typeof DashboardPlaygroundRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/demo/chat': typeof DemoChatRoute
  '/demo/object': typeof DemoObjectRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/chat'
    | '/api/gov-impact'
    | '/api/market-events'
    | '/api/object'
    | '/api/performance-failure'
    | '/api/performance-recipe'
    | '/api/portfolio-graph'
    | '/api/series'
    | '/dashboard/connectors'
    | '/dashboard/network'
    | '/dashboard/overview'
    | '/dashboard/playground'
    | '/dashboard/portfolio'
    | '/dashboard/settings'
    | '/demo/chat'
    | '/demo/object'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/gov-impact'
    | '/api/market-events'
    | '/api/object'
    | '/api/performance-failure'
    | '/api/performance-recipe'
    | '/api/portfolio-graph'
    | '/api/series'
    | '/dashboard/connectors'
    | '/dashboard/network'
    | '/dashboard/overview'
    | '/dashboard/playground'
    | '/dashboard/portfolio'
    | '/dashboard/settings'
    | '/demo/chat'
    | '/demo/object'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/api/chat'
    | '/api/gov-impact'
    | '/api/market-events'
    | '/api/object'
    | '/api/performance-failure'
    | '/api/performance-recipe'
    | '/api/portfolio-graph'
    | '/api/series'
    | '/dashboard/connectors'
    | '/dashboard/network'
    | '/dashboard/overview'
    | '/dashboard/playground'
    | '/dashboard/portfolio'
    | '/dashboard/settings'
    | '/demo/chat'
    | '/demo/object'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiGovImpactRoute: typeof ApiGovImpactRoute
  ApiMarketEventsRoute: typeof ApiMarketEventsRoute
  ApiObjectRoute: typeof ApiObjectRoute
  ApiPerformanceFailureRoute: typeof ApiPerformanceFailureRoute
  ApiPerformanceRecipeRoute: typeof ApiPerformanceRecipeRoute
  ApiPortfolioGraphRoute: typeof ApiPortfolioGraphRoute
  ApiSeriesRoute: typeof ApiSeriesRoute
  DemoChatRoute: typeof DemoChatRoute
  DemoObjectRoute: typeof DemoObjectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/demo/object': {
      id: '/demo/object'
      path: '/demo/object'
      fullPath: '/demo/object'
      preLoaderRoute: typeof DemoObjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/chat': {
      id: '/demo/chat'
      path: '/demo/chat'
      fullPath: '/demo/chat'
      preLoaderRoute: typeof DemoChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/portfolio': {
      id: '/dashboard/portfolio'
      path: '/portfolio'
      fullPath: '/dashboard/portfolio'
      preLoaderRoute: typeof DashboardPortfolioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/playground': {
      id: '/dashboard/playground'
      path: '/playground'
      fullPath: '/dashboard/playground'
      preLoaderRoute: typeof DashboardPlaygroundRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/overview': {
      id: '/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/network': {
      id: '/dashboard/network'
      path: '/network'
      fullPath: '/dashboard/network'
      preLoaderRoute: typeof DashboardNetworkRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/connectors': {
      id: '/dashboard/connectors'
      path: '/connectors'
      fullPath: '/dashboard/connectors'
      preLoaderRoute: typeof DashboardConnectorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/series': {
      id: '/api/series'
      path: '/api/series'
      fullPath: '/api/series'
      preLoaderRoute: typeof ApiSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portfolio-graph': {
      id: '/api/portfolio-graph'
      path: '/api/portfolio-graph'
      fullPath: '/api/portfolio-graph'
      preLoaderRoute: typeof ApiPortfolioGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/performance-recipe': {
      id: '/api/performance-recipe'
      path: '/api/performance-recipe'
      fullPath: '/api/performance-recipe'
      preLoaderRoute: typeof ApiPerformanceRecipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/performance-failure': {
      id: '/api/performance-failure'
      path: '/api/performance-failure'
      fullPath: '/api/performance-failure'
      preLoaderRoute: typeof ApiPerformanceFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/object': {
      id: '/api/object'
      path: '/api/object'
      fullPath: '/api/object'
      preLoaderRoute: typeof ApiObjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market-events': {
      id: '/api/market-events'
      path: '/api/market-events'
      fullPath: '/api/market-events'
      preLoaderRoute: typeof ApiMarketEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gov-impact': {
      id: '/api/gov-impact'
      path: '/api/gov-impact'
      fullPath: '/api/gov-impact'
      preLoaderRoute: typeof ApiGovImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardConnectorsRoute: typeof DashboardConnectorsRoute
  DashboardNetworkRoute: typeof DashboardNetworkRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardPlaygroundRoute: typeof DashboardPlaygroundRoute
  DashboardPortfolioRoute: typeof DashboardPortfolioRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardConnectorsRoute: DashboardConnectorsRoute,
  DashboardNetworkRoute: DashboardNetworkRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardPlaygroundRoute: DashboardPlaygroundRoute,
  DashboardPortfolioRoute: DashboardPortfolioRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiGovImpactRoute: ApiGovImpactRoute,
  ApiMarketEventsRoute: ApiMarketEventsRoute,
  ApiObjectRoute: ApiObjectRoute,
  ApiPerformanceFailureRoute: ApiPerformanceFailureRoute,
  ApiPerformanceRecipeRoute: ApiPerformanceRecipeRoute,
  ApiPortfolioGraphRoute: ApiPortfolioGraphRoute,
  ApiSeriesRoute: ApiSeriesRoute,
  DemoChatRoute: DemoChatRoute,
  DemoObjectRoute: DemoObjectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
